version: "3"
services:
  sc_docker:
    container_name: sc_docker
    build: .
    image: sc_docker
    tty: true
    stdin_open: true
    environment:
    - CPPUTEST_HOME=  
    volumes:
      - "./:/home/project"
